version: '3.8'

services:
  postgres:
    restart: always
    image: postgres:15.13-alpine
    container_name: stock_app
    shm_size: 1gb
    command: postgres -c 'max_connections=1000' -c 'wal_level=logical' -c 'wal_log_hints=on'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-AcSNetjbsKSbrbjNFMNtgF5rODjkOC9N}
      POSTGRES_DB: stock_app
    ports:
      - "54321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
